### ISSUE TITLE
Waisda? API statistics

### ISSUE THREAD

**Issue by rasvaan** [rasvaan/digibird_api#20]
Integrate the Waisda? API
- [ ] add correct information to platforms.json
- [ ] add to statistics switch
- [ ] write queries obtaining meta info
- [ ] embed properly in client

**Comment by LaraHack** [comment]
Link calls to http://waisda.beeldengeluid.nl/waisdadb

And DigiBird statistics will be here http://waisda.beeldengeluid.nl/waisdadb/statistics
